#!/bin/bash

BASE=`dirname $0`
CADB="${BASE}/db"

ROOTCA_SUBJ="/C=AU/O=Home Lab/OU=www.lab.home/CN=Home Lab Root"
ROOTCA=`echo "$ROOTCA_SUBJ" | sed 's/ = /=/g' | sed -n 's/^.*CN=//p' | sed 's/\/.*//' | sed 's/,.*//' | sed "s/\./_/g" | sed "s/\s\+/_/g"`
ROOTCA_CRT_URI="http://ca.lab.home/${ROOTCA}.crt"
ROOTCA_CRL_URI="http://ca.lab.home/${ROOTCA}.crl"

HOMECA_SUBJ="/C=AU/O=Home Lab/OU=www.lab.home/CN=Home Lab CA"
HOMECA=`echo "$HOMECA_SUBJ" | sed 's/ = /=/g' | sed -n 's/^.*CN=//p' | sed 's/\/.*//' | sed 's/,.*//' | sed "s/\./_/g" | sed "s/\s\+/_/g"`
HOMECA_CRT_URI="http://ca.lab.home/${HOMECA}.crt"
HOMECA_CRL_URI="http://ca.lab.home/${HOMECA}.crl"
HOMECA_OCSP="http://ocsp.lab.home"

DAYS=365
