#!/bin/bash

if [ "x$1" == "x" ]
then
  echo -e "Usage $0 certificate.common.name [subject.alternate.names] [subject.alternate.ipaddress]\n"
  exit
fi

URL=$1
FILE=`echo $URL | sed "s/\./_/g" | sed "s/\*/star/g" | sed 's/\/.*//'`
# Remove /emailAddress if it exists from URL
CN=`echo $URL | sed "s/\/.*//"`
SUBJ="/C=AU/ST=Western Australia/L=Perth/O=Home Lab/CN=$URL"

# If CN is a wildcard, add base domain as SAN.
if [[ $CN = "*."* ]]
then
  SAN="DNS:"`echo $CN | sed "s/\*\.//g"`
else # just add the CN
  SAN="DNS:"$CN
fi

if [ $# -gt 1 ]
then
    sans=($@)
    i=1
    while [ $i -lt ${#sans[@]} ]
    do
        if [[ ${sans[i]} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            SAN=${SAN},"IP:${sans[i]}"
        elif [[ ${sans[i]} =~ ":" ]]; then  # assume IPv6
            SAN=${SAN},"IP:${sans[i]}"
        else
            SAN=${SAN},"DNS:${sans[i]}"
        fi
        i=$[$i+1]
    done
fi

openssl req -new -newkey rsa:2048 -nodes \
  -out "$FILE.csr" \
  -keyout "$FILE.key" \
  -subj "$SUBJ" \
  -reqexts req_ext \
  -config <(cat \
  <(printf "[ req ]\n") \
  <(printf "distinguished_name=req\n") \
  <(printf "[ req_ext ]\n") \
  <(printf "keyUsage=critical,keyEncipherment,dataEncipherment\n") \
  <(printf "subjectKeyIdentifier=hash\n") \
  <(printf "subjectAltName=${SAN}\n") \
  )

