#!/bin/bash

if [ "x$1" == "x" ]
then
  echo -e "Usage $0 certificate.common.name [subject.alternate.name] [subject.alternate.ipaddress]\n"
  exit
fi

BASE=`dirname $0`
[[ -f $BASE/config ]] && source $BASE/config || echo "Configuration file $BASE/config was not found"

if [ "${CADB}x" == "x" ]
then
  echo "The Certifcate Authority DataBase folder is not defined. Exiting.."
  exit 1
fi

if [ ! -f ${CADB}/${HOMECA}.crt ]
then
  echo "${CADB}/${HOMECA}.crt doesn't exists. Please create it before running this script."
  exit 1
fi

URL=$1
FILE=`echo $URL | sed "s/\./_/g" | sed "s/\*/star/g" | sed 's/\/.*//'`
# Remove /emailAddress if it exists from URL
CN=`echo $URL | sed "s/\/.*//"`
SUBJ="/C=AU/ST=Western Australia/L=Perth/O=Home Lab/CN=$URL"

# If CN is a wildcard, add base domain as SAN.
if [[ $CN = "*."* ]]
then
  SAN="DNS:"`echo $CN | sed "s/\*\.//g"`
else # just add the CN
  SAN="DNS:"$CN
fi

# Add commandline subject alternates
if [ $# -gt 1 ]
then
    sans=($@)
    i=1
    while [ $i -lt ${#sans[@]} ]
    do
        if [[ ${sans[i]} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            SAN=${SAN},"IP:${sans[i]}"
        elif [[ ${sans[i]} =~ ":" ]]; then  # assume IPv6
            SAN=${SAN},"IP:${sans[i]}"
        else
            SAN=${SAN},"DNS:${sans[i]}"
        fi
        i=$[$i+1]
    done
fi

openssl req -newkey rsa:2048 -nodes \
  -keyout "$FILE.key" \
  -out "$FILE.csr" \
  -subj "$SUBJ"

REQFILE="$FILE.csr"
# openssl 1.0.x -> subject=/C=AU/ST=Western Australia/L=Perth/O=Home/OU=Lab/CN=www.lab.home
# openssl 1.1.x -> subject=C = AU, ST = Western Australia, L = Perth, O = Home, OU = Lab, CN = www.lab.home

COUNTRY=`openssl req -noout -subject -in "$REQFILE" | sed 's/ = /=/g' | sed -n '/^subject/s/^.*C=//p' | sed 's/\/.*//' | sed 's/,.*//'` 
STATE=`openssl req -noout -subject -in "$REQFILE" | sed 's/ = /=/g' | sed -n '/^subject/s/^.*ST=//p' | sed 's/\/.*//' | sed 's/,.*//'`
LOCATION=`openssl req -noout -subject -in "$REQFILE" | sed 's/ = /=/g' | sed -n '/^subject/s/^.*L=//p' | sed 's/\/.*//' | sed 's/,.*//'`
ORG=`openssl req -noout -subject -in "$REQFILE" | sed 's/ = /=/g' | sed -n '/^subject/s/^.*O=//p' | sed 's/\/.*//' | sed 's/,.*//'`
ORGUNIT=`openssl req -noout -subject -in "$REQFILE" | sed 's/ = /=/g' | sed -n '/^subject/s/^.*OU=//p' | sed 's/\/.*//' | sed 's/,.*//'`
CN=`openssl req -noout -subject -in "$REQFILE" | sed 's/ = /=/g' | sed -n '/^subject/s/^.*CN=//p' | sed 's/\/.*//' | sed 's/,.*//'`

NEWSUBJ="/OU=Domain Control Validated/OU=homelab/CN=${CN}"

openssl ca -batch -days $DAYS \
  -in "${FILE}.csr" \
  -out "${FILE}.crt" \
  -subj "${NEWSUBJ}" \
  -keyfile ${CADB}/${HOMECA}.key \
  -cert ${CADB}/${HOMECA}.crt \
  -name home_CA \
  -config <(cat <<EOF

[ home_CA ]
database               = ${CADB}/${HOMECA}.idx
unique_subject         = no
default_md             = sha256
serial                 = ${CADB}/${HOMECA}.srl
new_certs_dir          = ${CADB}/
policy                 = policy_DV

[ policy_DV ]
organizationalUnitName = optional
commonName             = supplied

EOF
  ) \
  -extensions exts \
  -extfile <(cat <<EOF
  
[ exts ]
authorityKeyIdentifier = keyid:always,issuer
subjectKeyIdentifier   = hash
subjectAltName         = $SAN
keyUsage               = critical,digitalSignature,keyEncipherment
extendedKeyUsage       = serverAuth,clientAuth
basicConstraints       = critical,CA:false
authorityInfoAccess    = OCSP;URI:${HOMECA_OCSP},caIssuers;URI:${HOMECA_CRL_URI}
crlDistributionPoints  = URI:${HOMECA_CRL_URI}
certificatePolicies    = 2.23.140.1.2.1

EOF
  )

openssl verify -CAfile <(cat ${CADB}/${HOMECA}.crt ${CADB}/${ROOTCA}.crt) $FILE.crt
