#!/bin/bash

if [ "x$1" == "x" ]
then
  echo -e "Usage $0 certificate.common.name[/emailAddress=] [subject.alternate.name] [subject.alternate.ipaddress]\n"
  exit
fi

URL=$1
FILE=`echo $URL | sed "s/\./_/g" | sed "s/\*/star/g" | sed 's/\/.*//'`
# Remove /emailAddress if it exists from URL
CN=`echo $URL | sed "s/\/.*//"`
SUBJ="/C=AU/ST=Western Australia/L=Perth/O=Local/CN=$URL"

# If CN is a wildcard, add base domain as SAN.
if [[ $CN = "*."* ]]
then
  SAN="DNS:"`echo $CN | sed "s/\*\.//g"`
else # just add the CN
  SAN="DNS:"$CN
fi

# Add commandline subject alternates
if [ $# -gt 1 ]
then
    sans=($@)
    i=1
    while [ $i -lt ${#sans[@]} ]
    do
        if [[ ${sans[i]} =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then  # assume IPv4
            SAN=${SAN},"IP:${sans[i]}"
        elif [[ ${sans[i]} =~ ":" ]]; then  # assume IPv6
            SAN=${SAN},"IP:${sans[i]}"
        else
            SAN=${SAN},"DNS:${sans[i]}"
        fi
        i=$[$i+1]
    done
fi

openssl req -new -x509 -newkey rsa:2048 -nodes -days $DAYS -sha256 \
  -subj "$SUBJ" \
  -out "$FILE.crt" \
  -keyout "$FILE.key" \
  -extensions exts \
  -config <(cat \
  <(printf "[ req ]\n") \
  <(printf "distinguished_name=req_distinguished_name\n") \
  <(printf "[ req_distinguished_name ]\n") \
  <(printf "[ exts ]\n") \
  <(printf "subjectKeyIdentifier=hash\n") \
  <(printf "authorityKeyIdentifier=keyid:always,issuer\n") \
  <(printf "subjectAltName=$SAN\n") \
  <(printf "keyUsage=critical,digitalSignature,keyEncipherment,keyCertSign\n") \
  <(printf "extendedKeyUsage=serverAuth,clientAuth\n") \
  <(printf "basicConstraints=critical,CA:true\n") \
  )

openssl verify -CAfile ${FILE}.crt ${FILE}.crt
